#ifndef PARSER_H
# define PARSER_H

typedef enum e_symbol_id
{
	// Terminals (generated by lexer)
	SYM_TOKEN,	// Not classified by the lexer
	SYM_NEWLINE,	// `\n`
	SYM_EOF,		// End of input
	// [...] to be extended with full terminals list
	//
	// Non-terminals (reduced by parser)
	SYM_PROGRAM,
	SYM_SIMPLE_COMMAND,
	SYM_CMD_NAME,
	SYM_CMD_SUFFIX,
	SYM_WORD,
	SYM_ERROR,
	SYM_COUNT
	// [...] to be extended with full non-terminals list
}	t_symbol_id;

typedef struct s_symbol
{
	t_symbol_id		id;
}	t_symbol;

#endif
