/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   scanner.h                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: adouieb <adouieb@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/04/20 16:05:23 by adouieb           #+#    #+#             */
/*   Updated: 2026/04/29 18:08:14 by adouieb          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef SCANNER_H
# define SCANNER_H

#include "libft.h"

// ---------- Token ----------

typedef enum e_token_type
{
	TOKEN,			// - Non-specific token (WORD, NAME, ASSIGNMENT_WORD, ...) that doesn't fit into other categories
	// control
	NEWLINE,		// `\n` - command separator
	SCOLON,			// `;`- command separator
	AMPERSAND,		// `&` - background command separator
	DSEMI,			// `;;` - case separator
	SEMI_AND,		// `;&` - case fallthrough
	AND_IF,			// `&&` - logical AND operator
	OR_IF,			// `||` - logical OR operator
	PIPE,			// `|` - pipeline operator
	LPARENTHESIS,	// `(` - subshell start
	RPARENTHESIS,	// `)` - subshell end
	EOF,			// \<EOF> - end of input	
	// redirection
	IO_NUMBER,	// `[0-9]+` - file descriptor for redirection
	LESSAND,	// `<&` - duplicate input file descriptor
	GREATAND,	// `>&` - duplicate output file descriptor
	LESS,		// `<` - input redirection
	GREAT,		// `>` - output redirection
	CLOBBER,	// `>|` - output redirection with clobbering (force overwrite)
	LESSGREAT,	// `<>` - input/output redirection
	DGREAT,	// `>>` - append redirection
	DLESS,		// `<<` - here document
	DLESSDASH	// `<<-` - here document with tab stripping
}	t_token_type;

typedef t_buff	t_token_value;	// The string value of the token (e.g., the actual word, operator, etc.)

typedef t_list t_tokens;
typedef t_node t_tokens_item;
typedef struct s_token
{
	t_token_type	type;	// Indicates which type of token this is
	size_t			offset;	// The raw string from the input that corresponds to this token (before any processing)
	t_token_value	value;
}	t_token;

void			free_token(void *token_ptr);

// ---------- Heredoc state ----------

typedef char*	t_file_path;

typedef t_list t_heredoc_stack;
typedef t_node t_heredoc_stack_item;
typedef struct s_heredoc
{
	int				fd;
	t_file_path		path;
	bool			expand;
	t_token_value	delimiter;
	size_t			body_size;	// The offset in the original input where the heredoc body starts (for error reporting)
	bool			strip_tabs;	// Indicates if leading tabs should be stripped from the input (for <<-)
}	t_heredoc;

// ---------- Lexer state ----------

typedef enum e_quote_mode
{
	NONE_,		// Not in a quote
	SINGLE_,	// In a single quote
	DOUBLE_,	// In a double quote
}	t_quote_mode;

typedef struct s_lexer
{
	size_t			index;	// Current position in the input string
	char			*input;	// The original input string being lexed
	t_quote_mode	quotes;	// Current quote mode
	t_tokens		saved;	// For heredoc handling
	t_tokens		tokens;	// List of tokens generated by the lexer
}	t_lexer;

// ------------ Reader API ------------

char			*read_line_continuation(void);

// ------------ Lexer API ------------

void			free_token(void *token_ptr);

void			lex_line(t_lexer *lexer, char *input);

t_token			*get_next_token(t_lexer *lexer);
t_token			*peek_token(t_lexer *lexer, size_t offset);

bool			is_token_stream_eof(t_lexer *lexer);

typedef struct s_add_heredoc
{
	t_token_value	delimiter;
	bool			strip_tabs;
}	t_add_heredoc;

void			read_heredoc_stack(void);
t_file_path		add_heredoc_to_stack(t_lexer *lexer, t_add_heredoc params);

#endif
